d  /var/home/redhat/.var                                                                    0755  redhat  redhat  -  -
d  /var/home/redhat/.var/app                                                                0755  redhat  redhat  -  -
d  /var/home/redhat/.var/app/org.libretro.RetroArch                                        0755  redhat  redhat  -  -
d  /var/home/redhat/.var/app/org.libretro.RetroArch/config                                 0755  redhat  redhat  -  -
d  /var/home/redhat/.var/app/org.libretro.RetroArch/config/retroarch                       0755  redhat  redhat  -  -
C  /var/home/redhat/.var/app/org.libretro.RetroArch/config/retroarch/retroarch.cfg         0644  redhat  redhat  -  /usr/share/arcade/retroarch.cfg
