FROM localhost/arcade-os:latest

# 1. Enable RHEL CodeReady Builder and install dependencies
RUN dnf config-manager --set-enabled codeready-builder-for-rhel-10-$(uname -m)-rpms && \
    dnf install -y \
        https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm

RUN dnf install -y \
        gcc gcc-c++ SDL2-devel SDL2_ttf-devel libXi-devel libXinerama-devel \
        qt5-qtbase-devel qt5-qttools expat-devel fontconfig-devel \
        alsa-lib-devel pulseaudio-libs-devel lld llvm \
    && dnf clean all

# 2. Build MAME
RUN git clone -b mame0286 --depth 1 https://github.com/mamedev/mame.git /opt/mame && \
    cd /opt/mame && make

# 3. Setup MAME config and ROM directory
RUN mkdir -p /opt/mame/roms /opt/arcade
COPY --chmod=644 mame.ini /opt/mame/mame.ini

# 4. Autostart script
COPY --chmod=755 mame_arcade.sh /opt/arcade/mame_arcade.sh

# 5. Populating autostart and applications for launching Arcade games
COPY --chmod=644 arcade_autostart.desktop /usr/share/arcade/arcade_autostart.desktop
COPY tmpfiles.d/ /usr/lib/tmpfiles.d/
