FROM registry.redhat.io/rhel10/rhel-bootc:10.1

# COPY the auth.json to enable the image to authenticate with GHCR
COPY ./auth.json /etc/ostree/

# Install RPMs and clean up the cache in the same layer to optimize the build process and reduce the image size by minimizing the number of layers created during the build process. This also helps in reducing the overall image size by minimizing the number of intermediate layers created during the build process.
RUN dnf -y install tmux mkpasswd git unzip \ 
    && dnf clean all

RUN pass=$(mkpasswd --method=SHA-512 --rounds=4096 redhat) && useradd -m -G wheel redhat -p $pass
RUN echo "%wheel        ALL=(ALL)       NOPASSWD: ALL" > /etc/sudoers.d/wheel-sudo

# Install GNOME and enable graphical.target as default
# As this is a dnf group install it will stay in a separate layer, but all the individual package installations will be combined in the next step to optimize the build process and reduce the image size.
RUN dnf group install -y --allowerasing GNOME Fonts && dnf clean all
RUN systemctl set-default graphical.target

# Remove GNOME initial setup and tour to avoid first boot pop-ups
RUN sudo dnf remove -y gnome-initial-setup gnome-tour

# Registering machine to Red Hat Insights
# Populate the .rhc_connect_credentials file with RHC_ACT_KEY=activation key and RHC_ORG_ID=organization id.
# See https://console.redhat.com/insights/connector/activation-keys
COPY rhc-connect.service /usr/lib/systemd/system/rhc-connect.service
COPY .rhc_connect_credentials /etc/rhc/.rhc_connect_credentials
RUN systemctl enable rhc-connect && touch /etc/rhc/.run_rhc_connect_next_boot

# Configuring autologin
COPY custom.conf /etc/gdm

# Configure the display resolution
# May have to be adjusted based on the monitor you are using. The current configuration is for 800x600 QEMU VM resolution, where the arcade game was full screen.
COPY monitors.xml /var/lib/gdm/.config/monitors.xml

# Turning off Automatic Overview when a user is logged into
COPY dash-to-dock.zip /tmp/
RUN mkdir -p /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com && \
    unzip /tmp/dash-to-dock.zip -d /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/ && \
    rm /tmp/dash-to-dock.zip

RUN ln -s /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml \
    /usr/share/glib-2.0/schemas/ && \
    glib-compile-schemas /usr/share/glib-2.0/schemas/
    
RUN mkdir -p /etc/dconf/profile && \
    printf "user-db:user\nsystem-db:local\n" > /etc/dconf/profile/user

RUN mkdir -p /etc/dconf/db/local.d/ && \
    printf "[org/gnome/shell/extensions/dash-to-dock]\ndisable-overview-on-startup=true\n" \
    > /etc/dconf/db/local.d/01-dash-to-dock

# Not working as expected, need to investigate further as the user is in /var/home/redhat    
# # Disabling screen lock
# RUN dconf write /org/gnome/desktop/screensaver lock-enabled "'false'"    
RUN printf "[org/gnome/desktop/screensaver]\nlock-enabled=false\n" \ 
   > /etc/dconf/db/local.d/02-lock-enable


# # Disable screen lock delay for VMs
# RUN dconf write /org/gnome/desktop/screensaver/lock-delay "'uint32 0'"
RUN printf "[org/gnome/desktop/screensaver]\nlock-delay=0\n" \
   > /etc/dconf/db/local.d/03-lock-delay
   
# # Disable screen power saving for VMs
# RUN dconf write /org/gnome/desktop/session/idle-delay "'uint32 0'"
RUN printf "[org/gnome/desktop/session]\nidle-delay=0\n" \
  > etc/dconf/db/local.d/04-idle-delay

RUN dconf update
