FROM localhost/arcade-os:latest

# 1. Install EPEL and dependencies
RUN dnf install -y \
        https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm \
        flatpak \
        wget \
    && dnf clean all

# 2. Configure Flathub and install RetroArch
# We add the remote and install the application system-wide
RUN flatpak remote-add flathub https://dl.flathub.org/repo/flathub.flatpakrepo && \
    flatpak install -y flathub org.libretro.RetroArch && \
    flatpak override --filesystem=/opt/retroarch org.libretro.RetroArch

# 3. Download Nestopia core
RUN mkdir -p /opt/retroarch/cores /opt/retroarch/roms && \
    wget -q "https://buildbot.libretro.com/nightly/linux/x86_64/latest/nestopia_libretro.so.zip" \
        -O /tmp/nestopia.zip && \
    unzip /tmp/nestopia.zip -d /opt/retroarch/cores && \
    rm /tmp/nestopia.zip

# 4. Autostart script
RUN mkdir -p /opt/arcade
COPY --chmod=755 retro_arcade.sh /opt/arcade/retro_arcade.sh

# 5. Pre-seed RetroArch config
COPY --chmod=644 retroarch.cfg /usr/share/arcade/retroarch.cfg

# 6. Populating autostart and applications for launching Arcade games
COPY --chmod=644 arcade_autostart.desktop /usr/share/arcade/arcade_autostart.desktop

COPY tmpfiles.d/ /usr/lib/tmpfiles.d/